[2024-08-03T12:39:24.537+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T12:39:24.581+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fill_tables_on_rd.End manual__2024-08-01T20:52:38.257006+00:00 [queued]>
[2024-08-03T12:39:24.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fill_tables_on_rd.End manual__2024-08-01T20:52:38.257006+00:00 [queued]>
[2024-08-03T12:39:24.595+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-03T12:39:24.615+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): End> on 2024-08-01 20:52:38.257006+00:00
[2024-08-03T12:39:24.624+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fill_tables_on_rd', 'End', 'manual__2024-08-01T20:52:38.257006+00:00', '--job-id', '766', '--raw', '--subdir', 'DAGS_FOLDER/fill_tables.py', '--cfg-path', '/tmp/tmpkkxf_l1j']
[2024-08-03T12:39:24.628+0000] {standard_task_runner.py:91} INFO - Job 766: Subtask End
[2024-08-03T12:39:24.628+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=296) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-03T12:39:24.629+0000] {standard_task_runner.py:63} INFO - Started process 299 to run task
[2024-08-03T12:39:24.691+0000] {task_command.py:426} INFO - Running <TaskInstance: fill_tables_on_rd.End manual__2024-08-01T20:52:38.257006+00:00 [running]> on host 2634975b7554
[2024-08-03T12:39:24.802+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fill_tables_on_rd' AIRFLOW_CTX_TASK_ID='End' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T20:52:38.257006+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T20:52:38.257006+00:00'
[2024-08-03T12:39:24.804+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T12:39:24.839+0000] {base.py:84} INFO - Using connection ID 'postgres_default2' for task execution.
[2024-08-03T12:39:24.873+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-03T12:39:24.874+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T12:39:24.887+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fill_tables_on_rd, task_id=End, run_id=manual__2024-08-01T20:52:38.257006+00:00, execution_date=20240801T205238, start_date=20240803T123924, end_date=20240803T123924
[2024-08-03T12:39:24.924+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-03T12:39:24.950+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T12:39:24.953+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
