[2024-08-01T20:53:19.844+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T20:53:19.887+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fill_tables_on_rd.fill_loan_holiday_info manual__2024-08-01T20:52:38.257006+00:00 [queued]>
[2024-08-01T20:53:19.901+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fill_tables_on_rd.fill_loan_holiday_info manual__2024-08-01T20:52:38.257006+00:00 [queued]>
[2024-08-01T20:53:19.902+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-01T20:53:19.918+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): fill_loan_holiday_info> on 2024-08-01 20:52:38.257006+00:00
[2024-08-01T20:53:19.928+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fill_tables_on_rd', 'fill_loan_holiday_info', 'manual__2024-08-01T20:52:38.257006+00:00', '--job-id', '752', '--raw', '--subdir', 'DAGS_FOLDER/fill_tables.py', '--cfg-path', '/tmp/tmpxgdpfyeh']
[2024-08-01T20:53:19.932+0000] {standard_task_runner.py:91} INFO - Job 752: Subtask fill_loan_holiday_info
[2024-08-01T20:53:19.932+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4486) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-01T20:53:19.933+0000] {standard_task_runner.py:63} INFO - Started process 4487 to run task
[2024-08-01T20:53:19.997+0000] {task_command.py:426} INFO - Running <TaskInstance: fill_tables_on_rd.fill_loan_holiday_info manual__2024-08-01T20:52:38.257006+00:00 [running]> on host 2634975b7554
[2024-08-01T20:53:20.104+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fill_tables_on_rd' AIRFLOW_CTX_TASK_ID='fill_loan_holiday_info' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T20:52:38.257006+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T20:52:38.257006+00:00'
[2024-08-01T20:53:20.106+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T20:53:20.124+0000] {sql.py:276} INFO - Executing: 
    call dm.refresh_loan_holiday_info();
    
[2024-08-01T20:53:20.138+0000] {base.py:84} INFO - Using connection ID 'postgres_default2' for task execution.
[2024-08-01T20:53:20.181+0000] {base.py:84} INFO - Using connection ID 'postgres_default2' for task execution.
[2024-08-01T20:53:20.190+0000] {sql.py:487} INFO - Running statement: 
    call dm.refresh_loan_holiday_info();
    , parameters: None
[2024-08-01T20:53:20.442+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T20:53:20.443+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidTransactionTermination: invalid transaction termination
CONTEXT:  PL/pgSQL function dm.refresh_loan_holiday_info() line 108 at COMMIT

[2024-08-01T20:53:20.467+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fill_tables_on_rd, task_id=fill_loan_holiday_info, run_id=manual__2024-08-01T20:52:38.257006+00:00, execution_date=20240801T205238, start_date=20240801T205319, end_date=20240801T205320
[2024-08-01T20:53:20.487+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 752 for task fill_loan_holiday_info (invalid transaction termination
CONTEXT:  PL/pgSQL function dm.refresh_loan_holiday_info() line 108 at COMMIT
; 4487)
[2024-08-01T20:53:20.507+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-01T20:53:20.523+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-01T20:53:20.543+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T20:53:20.546+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
