[2024-08-01T15:15:29.744+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T15:15:29.798+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fill_tables_on_rd.Start manual__2024-08-01T15:15:26.786282+00:00 [queued]>
[2024-08-01T15:15:29.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fill_tables_on_rd.Start manual__2024-08-01T15:15:26.786282+00:00 [queued]>
[2024-08-01T15:15:29.813+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-01T15:15:29.835+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Start> on 2024-08-01 15:15:26.786282+00:00
[2024-08-01T15:15:29.845+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fill_tables_on_rd', 'Start', 'manual__2024-08-01T15:15:26.786282+00:00', '--job-id', '739', '--raw', '--subdir', 'DAGS_FOLDER/fill_tables.py', '--cfg-path', '/tmp/tmp5oardv3b']
[2024-08-01T15:15:29.848+0000] {standard_task_runner.py:91} INFO - Job 739: Subtask Start
[2024-08-01T15:15:29.848+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2210) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-01T15:15:29.849+0000] {standard_task_runner.py:63} INFO - Started process 2211 to run task
[2024-08-01T15:15:29.906+0000] {task_command.py:426} INFO - Running <TaskInstance: fill_tables_on_rd.Start manual__2024-08-01T15:15:26.786282+00:00 [running]> on host 2634975b7554
[2024-08-01T15:15:30.009+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fill_tables_on_rd' AIRFLOW_CTX_TASK_ID='Start' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T15:15:26.786282+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T15:15:26.786282+00:00'
[2024-08-01T15:15:30.010+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T15:15:30.047+0000] {base.py:84} INFO - Using connection ID 'postgres_default2' for task execution.
[2024-08-01T15:15:35.093+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-01T15:15:35.101+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T15:15:35.196+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fill_tables_on_rd, task_id=Start, run_id=manual__2024-08-01T15:15:26.786282+00:00, execution_date=20240801T151526, start_date=20240801T151529, end_date=20240801T151535
[2024-08-01T15:15:35.386+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-01T15:15:35.467+0000] {taskinstance.py:3503} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-08-01T15:15:35.470+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
